# Generated by Django 4.2.3 on 2023-07-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=40, unique=True)),
                ('enName', models.CharField(max_length=40)),
                ('thName', models.CharField(max_length=40)),
            ],
        ),
    ]
